name: qoder-auto-review
triggers:
  merge_request:
    target-branches: '**'
    types:
      - opened
      - reopened
jobs:
  auto-review:
    steps:
      - uses: checkout
      - run: |
            git fetch
      - uses: run-qoder-cli@develop
        inputs:
          repo: ${{git.repo}}
          source_branch: ${{git.merge_request.sourceBranch}}
          target_branch: ${{git.merge_request.targetBranch}}
          mr_id: ${{git.merge_request.id}}
          mr_title: ${{git.merge_request.title}}
          project_id: ${{git.projectId}}
          scene: "cr"
          settings: '{"exclude_files": [".aoneci", ".github", ".lingma-agents.yaml"], "skip": {"max_commits": 30}}'
