name: qoder-auto-review
triggers:
  merge_request:
    target-branches: '**'
    types:
      - opened
      - reopened
jobs:
  auto-review:
    steps:
      - uses: checkout
        inputs:
          fetch-depth: 0
      - uses: run-qoder-cli@1.0.0
        inputs:
          settings: '{"exclude_files": [".aoneci", ".github", ".lingma-agents.yaml"], "skip": {"max_commits": 100}}'
