name: qoder-auto-review
triggers:
  merge_request:
    target-branches: '**'
    types:
      - opened
      - reopened
jobs:
  auto-review:
    steps:
      - uses: checkout
        inputs:
          fetch-depth: 0
      - run: |
          timeout 5 bash -c 'cat < /dev/null > /dev/tcp/pgm-bp149b9eo4m087l5to.pg.rds.aliyuncs.com/5432' && echo "ok" || echo "fail"
      - uses: run-qoder-cli@develop
        inputs:
          repo: ${{git.repo}}
          source_branch: ${{git.merge_request.sourceBranch}}
          target_branch: ${{git.merge_request.targetBranch}}
          mr_id: ${{git.merge_request.id}}
          mr_title: ${{git.merge_request.title}}
          project_id: ${{git.projectId}}
          scene: "cr"
          settings: '{"exclude_files": [".aoneci", ".github", ".lingma-agents.yaml"], "skip": {"max_commits": 30}}'
