CREATE TABLE IF NOT EXISTS attribute_value (
     id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
     attribute_id BIGINT UNSIGNED NOT NULL COMMENT '关联属性ID',
     value VARCHAR(255) NOT NULL COMMENT '属性值内容',
     sort_score INT NOT NULL DEFAULT 0 COMMENT '排序权重分值',
     created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
     updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
     PRIMARY KEY (id),
     INDEX idx_attribute_id (attribute_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商品属性值表';
